name: kwant-latest
channels:
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - numpy
    - scipy
    - tinyarray
    - sympy
    - matplotlib-base
    - plotly
    - qsymm
    # Linear algebra libraraies
    - mumps-seq
    - mumps-include
    - blas #=1.1 openblas
    - openblas #=0.2.20
    # Build toolchain
    - toolchain3
    - cython
    - libgfortran
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
    # Documentation building
    - numpydoc
    - requests
    - jupyter_sphinx
    - pip:
        - git+https://github.com/sphinx-doc/sphinx.git@bedbb8c8259f1b4520ed654ffda3a045c55163d7
        - sphinxcontrib-svg2pdfconverter
